#!/usr/bin/env python3
#
#  Copyright (C) 2010 - Librix Dev Team
#
# This file is part of librix-thinclient.
#
# librix-thinclient is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# librix-thinclient is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
#
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with librix-thinclient.  If not, see <http://www.gnu.org/licenses/>.

import sys
from os.path import isfile,abspath,isdir
from os import kill,remove
from argparse import ArgumentParser

if isdir("./build/lib/ltmt"):
	sys.path.append("./build/lib")

from ltmt.defs import pidfile, version

if __name__ == "__main__":
	description = "Librix ThinClient Management Tool (LTMT)"

	parser = ArgumentParser(description=description)

	mgroup = parser.add_argument_group(title="Init method")
	mode_group = mgroup.add_mutually_exclusive_group(required=True)
	mode_group.add_argument("-c", "--client", dest="mode", action="store_const",
		const=0, help="Executes LTMT GUI Interface")
	mode_group.add_argument("-d", "--daemon", dest="mode", action="store_const",
		const=1, help="Executes LTMT Daemon")
	mode_group.add_argument("-k", "--kill-daemon", dest="mode",
		action="store_const", const=2, help="Kill LTMT Daemon")

	group = parser.add_argument_group(title="Debug Options")
	dbg_group = group.add_mutually_exclusive_group()
	dbg_group.add_argument("-q", "--quiet", dest="verbose", default=False,
		action="store_false", help="Suppress debug informations")
	dbg_group.add_argument("-v", "--verbose", dest="verbose", default=False,
		action="store_true", help="Show debug informations")

	parser.add_argument("-f", "--configfile", default="/etc/thinclient.conf",
		nargs=1, help="Configuration File", metavar="FILE")
	parser.add_argument("-V", "--version", action="version",
		version="Librix ThinClient Management Tool v{0}".format(version))

	options = parser.parse_args()

	if not options.verbose:
		sys.stdout = open("/dev/null", "w")
		sys.stderr = open("/dev/null", "w")

	configfile = None
	if isfile(options.configfile[0]):
		configfile = abspath(options.configfile[0])

	if options.mode == 0:		# if 0, client mode
		from ltmt.ui.main import main
		main(configfile)
	elif options.mode == 1:	# elif 1, daemon mode
		from ltmt.daemon.tcd import main
		main(configfile)
	elif options.mode == 2:	# elif 2, kill daemon
		if isfile(pidfile):
			with open(pidfile, "r") as P:
				kill(int(P.read().strip()), 9)
				#except: pass
			remove(pidfile)
		else:
			print("Daemon not running!!!")
