# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editWidget.ui'
#
# Created: Wed Oct  6 16:41:38 2010
#      by: PyQt4 UI code generator 4.7.7
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
	_fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
	_fromUtf8 = lambda s: s

class Ui_EditWidget(object):
	def setupUi(self, EditWidget):
		EditWidget.setObjectName(_fromUtf8("EditWidget"))
		EditWidget.resize(500, 430)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(EditWidget.sizePolicy().hasHeightForWidth())
		EditWidget.setSizePolicy(sizePolicy)
		self.verticalLayout = QtGui.QVBoxLayout(EditWidget)
		self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
		self.editWidget = QtGui.QWidget(EditWidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.editWidget.sizePolicy().hasHeightForWidth())
		self.editWidget.setSizePolicy(sizePolicy)
		self.editWidget.setObjectName(_fromUtf8("editWidget"))
		self.horizontalLayout = QtGui.QHBoxLayout(self.editWidget)
		self.horizontalLayout.setMargin(0)
		self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
		self.profilesListWidget = QtGui.QWidget(self.editWidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.profilesListWidget.sizePolicy().hasHeightForWidth())
		self.profilesListWidget.setSizePolicy(sizePolicy)
		self.profilesListWidget.setMaximumSize(QtCore.QSize(200, 16777215))
		self.profilesListWidget.setObjectName(_fromUtf8("profilesListWidget"))
		self.verticalLayout_3 = QtGui.QVBoxLayout(self.profilesListWidget)
		self.verticalLayout_3.setMargin(0)
		self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
		self.profilesLabel = QtGui.QLabel(self.profilesListWidget)
		self.profilesLabel.setObjectName(_fromUtf8("profilesLabel"))
		self.verticalLayout_3.addWidget(self.profilesLabel)
		self.listView = QtGui.QListView(self.profilesListWidget)
		self.listView.setObjectName(_fromUtf8("listView"))
		self.verticalLayout_3.addWidget(self.listView)
		self.EditToolBarWidget = QtGui.QWidget(self.profilesListWidget)
		self.EditToolBarWidget.setObjectName(_fromUtf8("EditToolBarWidget"))
		self.horizontalLayout_2 = QtGui.QHBoxLayout(self.EditToolBarWidget)
		self.horizontalLayout_2.setMargin(0)
		self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
		self.verticalLayout_3.addWidget(self.EditToolBarWidget)
		self.horizontalLayout.addWidget(self.profilesListWidget)
		self.editProfilesWidget = QtGui.QWidget(self.editWidget)
		self.editProfilesWidget.setObjectName(_fromUtf8("editProfilesWidget"))
		self.verticalLayout_4 = QtGui.QVBoxLayout(self.editProfilesWidget)
		self.verticalLayout_4.setMargin(0)
		self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
		self.toolBox = QtGui.QToolBox(self.editProfilesWidget)
		self.toolBox.setObjectName(_fromUtf8("toolBox"))
		self.hardwarePage = QtGui.QWidget()
		self.hardwarePage.setGeometry(QtCore.QRect(0, 0, 278, 358))
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.hardwarePage.sizePolicy().hasHeightForWidth())
		self.hardwarePage.setSizePolicy(sizePolicy)
		self.hardwarePage.setObjectName(_fromUtf8("hardwarePage"))
		self.gridLayout = QtGui.QGridLayout(self.hardwarePage)
		self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
		self.pushButton = QtGui.QPushButton(self.hardwarePage)
		self.pushButton.setCheckable(True)
		self.pushButton.setObjectName(_fromUtf8("pushButton"))
		self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
		self.pushButton_2 = QtGui.QPushButton(self.hardwarePage)
		self.pushButton_2.setCheckable(True)
		self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
		self.gridLayout.addWidget(self.pushButton_2, 1, 0, 1, 1)
		self.pushButton_3 = QtGui.QPushButton(self.hardwarePage)
		self.pushButton_3.setCheckable(True)
		self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
		self.gridLayout.addWidget(self.pushButton_3, 2, 0, 1, 1)
		self.pushButton_4 = QtGui.QPushButton(self.hardwarePage)
		self.pushButton_4.setCheckable(True)
		self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
		self.gridLayout.addWidget(self.pushButton_4, 3, 0, 1, 1)
		self.pushButton_5 = QtGui.QPushButton(self.hardwarePage)
		self.pushButton_5.setCheckable(True)
		self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
		self.gridLayout.addWidget(self.pushButton_5, 4, 0, 1, 1)
		self.pushButton_6 = QtGui.QPushButton(self.hardwarePage)
		self.pushButton_6.setCheckable(True)
		self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
		self.gridLayout.addWidget(self.pushButton_6, 0, 1, 1, 1)
		self.pushButton_7 = QtGui.QPushButton(self.hardwarePage)
		self.pushButton_7.setCheckable(True)
		self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
		self.gridLayout.addWidget(self.pushButton_7, 1, 1, 1, 1)
		self.pushButton_8 = QtGui.QPushButton(self.hardwarePage)
		self.pushButton_8.setCheckable(True)
		self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
		self.gridLayout.addWidget(self.pushButton_8, 2, 1, 1, 1)
		self.pushButton_9 = QtGui.QPushButton(self.hardwarePage)
		self.pushButton_9.setCheckable(True)
		self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
		self.gridLayout.addWidget(self.pushButton_9, 3, 1, 1, 1)
		self.pushButton_10 = QtGui.QPushButton(self.hardwarePage)
		self.pushButton_10.setCheckable(True)
		self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
		self.gridLayout.addWidget(self.pushButton_10, 4, 1, 1, 1)
		self.toolBox.addItem(self.hardwarePage, _fromUtf8(""))
		self.softwarePage = QtGui.QWidget()
		self.softwarePage.setGeometry(QtCore.QRect(0, 0, 278, 358))
		self.softwarePage.setObjectName(_fromUtf8("softwarePage"))
		self.gridLayout_2 = QtGui.QGridLayout(self.softwarePage)
		self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
		self.pushButton_11 = QtGui.QPushButton(self.softwarePage)
		self.pushButton_11.setCheckable(True)
		self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
		self.gridLayout_2.addWidget(self.pushButton_11, 0, 0, 1, 1)
		self.pushButton_12 = QtGui.QPushButton(self.softwarePage)
		self.pushButton_12.setCheckable(True)
		self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
		self.gridLayout_2.addWidget(self.pushButton_12, 1, 0, 1, 1)
		self.pushButton_13 = QtGui.QPushButton(self.softwarePage)
		self.pushButton_13.setCheckable(True)
		self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
		self.gridLayout_2.addWidget(self.pushButton_13, 2, 0, 1, 1)
		self.pushButton_14 = QtGui.QPushButton(self.softwarePage)
		self.pushButton_14.setCheckable(True)
		self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
		self.gridLayout_2.addWidget(self.pushButton_14, 3, 0, 1, 1)
		self.pushButton_15 = QtGui.QPushButton(self.softwarePage)
		self.pushButton_15.setCheckable(True)
		self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
		self.gridLayout_2.addWidget(self.pushButton_15, 0, 1, 1, 1)
		self.pushButton_16 = QtGui.QPushButton(self.softwarePage)
		self.pushButton_16.setCheckable(True)
		self.pushButton_16.setObjectName(_fromUtf8("pushButton_16"))
		self.gridLayout_2.addWidget(self.pushButton_16, 1, 1, 1, 1)
		self.pushButton_17 = QtGui.QPushButton(self.softwarePage)
		self.pushButton_17.setCheckable(True)
		self.pushButton_17.setObjectName(_fromUtf8("pushButton_17"))
		self.gridLayout_2.addWidget(self.pushButton_17, 2, 1, 1, 1)
		self.pushButton_18 = QtGui.QPushButton(self.softwarePage)
		self.pushButton_18.setCheckable(True)
		self.pushButton_18.setObjectName(_fromUtf8("pushButton_18"))
		self.gridLayout_2.addWidget(self.pushButton_18, 3, 1, 1, 1)
		self.toolBox.addItem(self.softwarePage, _fromUtf8(""))
		self.verticalLayout_4.addWidget(self.toolBox)
		self.horizontalLayout.addWidget(self.editProfilesWidget)
		self.verticalLayout.addWidget(self.editWidget)

		self.retranslateUi(EditWidget)
		self.toolBox.setCurrentIndex(1)
		QtCore.QMetaObject.connectSlotsByName(EditWidget)

	def retranslateUi(self, EditWidget):
		EditWidget.setWindowTitle(QtGui.QApplication.translate("EditWidget", "Form", None, QtGui.QApplication.UnicodeUTF8))
		self.profilesLabel.setText(QtGui.QApplication.translate("EditWidget", "Profiles:", None, QtGui.QApplication.UnicodeUTF8))
		self.pushButton.setText(QtGui.QApplication.translate("EditWidget", "Option", None, QtGui.QApplication.UnicodeUTF8))
		self.pushButton_2.setText(QtGui.QApplication.translate("EditWidget", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
		self.pushButton_3.setText(QtGui.QApplication.translate("EditWidget", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
		self.pushButton_4.setText(QtGui.QApplication.translate("EditWidget", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
		self.pushButton_5.setText(QtGui.QApplication.translate("EditWidget", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
		self.pushButton_6.setText(QtGui.QApplication.translate("EditWidget", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
		self.pushButton_7.setText(QtGui.QApplication.translate("EditWidget", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
		self.pushButton_8.setText(QtGui.QApplication.translate("EditWidget", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
		self.pushButton_9.setText(QtGui.QApplication.translate("EditWidget", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
		self.pushButton_10.setText(QtGui.QApplication.translate("EditWidget", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
		self.toolBox.setItemText(self.toolBox.indexOf(self.hardwarePage), QtGui.QApplication.translate("EditWidget", "Hardware", None, QtGui.QApplication.UnicodeUTF8))
		self.pushButton_11.setText(QtGui.QApplication.translate("EditWidget", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
		self.pushButton_12.setText(QtGui.QApplication.translate("EditWidget", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
		self.pushButton_13.setText(QtGui.QApplication.translate("EditWidget", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
		self.pushButton_14.setText(QtGui.QApplication.translate("EditWidget", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
		self.pushButton_15.setText(QtGui.QApplication.translate("EditWidget", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
		self.pushButton_16.setText(QtGui.QApplication.translate("EditWidget", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
		self.pushButton_17.setText(QtGui.QApplication.translate("EditWidget", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
		self.pushButton_18.setText(QtGui.QApplication.translate("EditWidget", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
		self.toolBox.setItemText(self.toolBox.indexOf(self.softwarePage), QtGui.QApplication.translate("EditWidget", "Software", None, QtGui.QApplication.UnicodeUTF8))

from . import temp_icons_rc
