# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/export/exportWidget.ui'
#
# Created: Mon Nov 29 17:15:35 2010
#      by: PyQt4 UI code generator 4.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
	_fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
	_fromUtf8 = lambda s: s

class Ui_ExportWidget(object):
	def setupUi(self, ExportWidget):
		ExportWidget.setObjectName(_fromUtf8("ExportWidget"))
		ExportWidget.resize(650, 550)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(ExportWidget.sizePolicy().hasHeightForWidth())
		ExportWidget.setSizePolicy(sizePolicy)
		self.mainVLayout = QtGui.QVBoxLayout(ExportWidget)
		self.mainVLayout.setMargin(4)
		self.mainVLayout.setObjectName(_fromUtf8("mainVLayout"))
		self.localremoteTab = QtGui.QTabWidget(ExportWidget)
		self.localremoteTab.setIconSize(QtCore.QSize(24, 24))
		self.localremoteTab.setObjectName(_fromUtf8("localremoteTab"))
		self.localTab = QtGui.QWidget()
		self.localTab.setObjectName(_fromUtf8("localTab"))
		self.verticalLayout = QtGui.QVBoxLayout(self.localTab)
		self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
		self.localImportBox = QtGui.QGroupBox(self.localTab)
		self.localImportBox.setObjectName(_fromUtf8("localImportBox"))
		self.verticalLayout_3 = QtGui.QVBoxLayout(self.localImportBox)
		self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
		self.localImportPathSelect = QtGui.QWidget(self.localImportBox)
		self.localImportPathSelect.setObjectName(_fromUtf8("localImportPathSelect"))
		self.horizontalLayout = QtGui.QHBoxLayout(self.localImportPathSelect)
		self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
		self.pathlabel = QtGui.QLabel(self.localImportPathSelect)
		self.pathlabel.setObjectName(_fromUtf8("pathlabel"))
		self.horizontalLayout.addWidget(self.pathlabel)
		self.pathLineEdit = QtGui.QLineEdit(self.localImportPathSelect)
		self.pathLineEdit.setText(_fromUtf8("/etc/thinclient.conf"))
		self.pathLineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.pathLineEdit.setObjectName(_fromUtf8("pathLineEdit"))
		self.horizontalLayout.addWidget(self.pathLineEdit)
		self.browseButton = QtGui.QToolButton(self.localImportPathSelect)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/export_icon/open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.browseButton.setIcon(icon)
		self.browseButton.setIconSize(QtCore.QSize(24, 24))
		self.browseButton.setAutoRaise(True)
		self.browseButton.setObjectName(_fromUtf8("browseButton"))
		self.horizontalLayout.addWidget(self.browseButton)
		self.verticalLayout_3.addWidget(self.localImportPathSelect)
		self.localImportButtonBox = QtGui.QDialogButtonBox(self.localImportBox)
		self.localImportButtonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Reset)
		self.localImportButtonBox.setObjectName(_fromUtf8("localImportButtonBox"))
		self.verticalLayout_3.addWidget(self.localImportButtonBox)
		self.verticalLayout.addWidget(self.localImportBox)
		self.localExportBox = QtGui.QGroupBox(self.localTab)
		self.localExportBox.setObjectName(_fromUtf8("localExportBox"))
		self.verticalLayout_4 = QtGui.QVBoxLayout(self.localExportBox)
		self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
		self.localExportPathSelect = QtGui.QWidget(self.localExportBox)
		self.localExportPathSelect.setObjectName(_fromUtf8("localExportPathSelect"))
		self.horizontalLayout_2 = QtGui.QHBoxLayout(self.localExportPathSelect)
		self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
		self.pathlabel_2 = QtGui.QLabel(self.localExportPathSelect)
		self.pathlabel_2.setObjectName(_fromUtf8("pathlabel_2"))
		self.horizontalLayout_2.addWidget(self.pathlabel_2)
		self.pathLineEdit_2 = QtGui.QLineEdit(self.localExportPathSelect)
		self.pathLineEdit_2.setText(_fromUtf8("/etc/thinclient.conf"))
		self.pathLineEdit_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.pathLineEdit_2.setObjectName(_fromUtf8("pathLineEdit_2"))
		self.horizontalLayout_2.addWidget(self.pathLineEdit_2)
		self.saveButton = QtGui.QToolButton(self.localExportPathSelect)
		icon1 = QtGui.QIcon()
		icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/export_icon/save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.saveButton.setIcon(icon1)
		self.saveButton.setIconSize(QtCore.QSize(24, 24))
		self.saveButton.setAutoRaise(True)
		self.saveButton.setObjectName(_fromUtf8("saveButton"))
		self.horizontalLayout_2.addWidget(self.saveButton)
		self.verticalLayout_4.addWidget(self.localExportPathSelect)
		self.localExportButtonBox = QtGui.QDialogButtonBox(self.localExportBox)
		self.localExportButtonBox.setStandardButtons(QtGui.QDialogButtonBox.Reset|QtGui.QDialogButtonBox.Save)
		self.localExportButtonBox.setObjectName(_fromUtf8("localExportButtonBox"))
		self.verticalLayout_4.addWidget(self.localExportButtonBox)
		self.verticalLayout.addWidget(self.localExportBox)
		icon2 = QtGui.QIcon()
		icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/tab/harddisk.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.localremoteTab.addTab(self.localTab, icon2, _fromUtf8(""))
		self.remoteTab = QtGui.QWidget()
		self.remoteTab.setObjectName(_fromUtf8("remoteTab"))
		self.verticalLayout_2 = QtGui.QVBoxLayout(self.remoteTab)
		self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
		self.remoteImportBox = QtGui.QGroupBox(self.remoteTab)
		self.remoteImportBox.setObjectName(_fromUtf8("remoteImportBox"))
		self.verticalLayout_5 = QtGui.QVBoxLayout(self.remoteImportBox)
		self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
		self.verticalLayout_2.addWidget(self.remoteImportBox)
		self.remoteExportBox = QtGui.QGroupBox(self.remoteTab)
		self.remoteExportBox.setObjectName(_fromUtf8("remoteExportBox"))
		self.verticalLayout_6 = QtGui.QVBoxLayout(self.remoteExportBox)
		self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
		self.verticalLayout_2.addWidget(self.remoteExportBox)
		icon3 = QtGui.QIcon()
		icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/tab/network.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.localremoteTab.addTab(self.remoteTab, icon3, _fromUtf8(""))
		self.mainVLayout.addWidget(self.localremoteTab)

		self.retranslateUi(ExportWidget)
		self.localremoteTab.setCurrentIndex(0)
		QtCore.QObject.connect(self.browseButton, QtCore.SIGNAL(_fromUtf8("clicked()")), ExportWidget.localImportBrowseFiles)
		QtCore.QObject.connect(self.localImportButtonBox, QtCore.SIGNAL(_fromUtf8("clicked(QAbstractButton*)")), ExportWidget.localImportClickedButton)
		QtCore.QObject.connect(self.pathLineEdit, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), ExportWidget.localImportCheckFile)
		QtCore.QObject.connect(self.saveButton, QtCore.SIGNAL(_fromUtf8("clicked()")), ExportWidget.localExportBrowseFiles)
		QtCore.QObject.connect(self.localExportButtonBox, QtCore.SIGNAL(_fromUtf8("clicked(QAbstractButton*)")), ExportWidget.localExportClickedButton)
		QtCore.QObject.connect(self.pathLineEdit_2, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), ExportWidget.localExportCheckFile)
		QtCore.QMetaObject.connectSlotsByName(ExportWidget)

	def retranslateUi(self, ExportWidget):
		ExportWidget.setWindowTitle(QtGui.QApplication.translate("ExportWidget", "Form", None, QtGui.QApplication.UnicodeUTF8))
		self.localImportBox.setTitle(QtGui.QApplication.translate("ExportWidget", "Import local file:", None, QtGui.QApplication.UnicodeUTF8))
		self.pathlabel.setText(QtGui.QApplication.translate("ExportWidget", "File Path:", None, QtGui.QApplication.UnicodeUTF8))
		self.browseButton.setText(QtGui.QApplication.translate("ExportWidget", "Browse", None, QtGui.QApplication.UnicodeUTF8))
		self.localExportBox.setTitle(QtGui.QApplication.translate("ExportWidget", "Export local file:", None, QtGui.QApplication.UnicodeUTF8))
		self.pathlabel_2.setText(QtGui.QApplication.translate("ExportWidget", "File Path:", None, QtGui.QApplication.UnicodeUTF8))
		self.saveButton.setText(QtGui.QApplication.translate("ExportWidget", "Browse", None, QtGui.QApplication.UnicodeUTF8))
		self.localremoteTab.setTabText(self.localremoteTab.indexOf(self.localTab), QtGui.QApplication.translate("ExportWidget", "Local", None, QtGui.QApplication.UnicodeUTF8))
		self.remoteImportBox.setTitle(QtGui.QApplication.translate("ExportWidget", "Remote Import Configuration:", None, QtGui.QApplication.UnicodeUTF8))
		self.remoteExportBox.setTitle(QtGui.QApplication.translate("ExportWidget", "Export to Network:", None, QtGui.QApplication.UnicodeUTF8))
		self.localremoteTab.setTabText(self.localremoteTab.indexOf(self.remoteTab), QtGui.QApplication.translate("ExportWidget", "Remote", None, QtGui.QApplication.UnicodeUTF8))

from ui.icons import temp_icons_rc

if __name__ == "__main__":
	import sys
	app = QtGui.QApplication(sys.argv)
	ExportWidget = QtGui.QWidget()
	ui = Ui_ExportWidget()
	ui.setupUi(ExportWidget)
	ExportWidget.show()
	sys.exit(app.exec_())

